### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chekoduadarsh** [chekoduadarsh/Optimization_of_Retinex_Algorithm#1]
Hey guys, This is an open Repo for image-processing and video processing optimization enthusiast, If you anything to contribute put an issue lets have a talk or put a pull request. 
Note:- This repo is not concentrated on the Retinex Algorithm only if there are other image processing algorithms we will update the readme and project title according to the updates to come and first timers dont worry much put your effort and pull your ideas

- [ ] Implementing more video processing algorithms
- [ ] Implementation in Laptops (PC) and comparison
- [ ] Comparison Between pthreads vs thread in performance
- [ ] Implementation of OpenMP
